### ISSUE TITLE
Possible Bug: not handling question mark

### ISSUE THREAD

**Issue by dhruvbatra** [avisingh599/visual-qa#11]
It's possible I'm mistaken, but it seems there's a bug in the way word embeddings are being computed in own_image.py

```
       question = unicode(raw_input("Ask a question: "))
       X_q = get_questions_tensor_timeseries([question], nlp, timesteps)
```

If question = "what color is the cat?"

the word "cat?" will considered out of vocabulary (due to lack of space before question mark) and word embeddings will be an all zero vector.

**Comment by avisingh599** [comment]
spaCy, the library I used for the NLP part, takes care of the lack of space. Its tokenization takes care of questions marks, apostrophes, lowering the case etc.

**Comment by dhruvbatra** [comment]
Hmm. True. Then there's some else going on because I am seeing the last vector as all zero.

**Comment by dhruvbatra** [comment]
Closing for now.

**Comment by avisingh599** [comment]
The last all zeros corresponds to the question mark.

**Comment by dhruvbatra** [comment]
Got it. It feels like an odd representation of that symbol, but thanks.
