### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../models/labelencoder.pkl'

### ISSUE THREAD

**Issue by merryHunter** [avisingh599/visual-qa#26]
Hello! I' trying to run own_images.py , but I receive this error:
`Traceback (most recent call last):
  File "own_image.py", line 65, in <module>
    main()
  File "own_image.py", line 31, in main
    labelencoder = joblib.load('../models/labelencoder.pkl')
  File "/home/ivan/PycharmProjects/visual-qa/env/local/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 409, in load
    with open(filename, 'rb') as file_handle:
IOError: [Errno 2] No such file or directory: '../models/labelencoder.pkl'
`
 Did you move this file? Can you help me to fix that?

**Comment by hitesha14** [comment]
hello @merryHunter: Please could you let me know about the location of   '../models/labelencoder.pkl'. I am facing the same issue. Were you able to resolve it?

hello @avisingh599: While running the program, I encounter the same issue as mentioned above, is there any method to resolve it or where can i find the .pkl file?

**Comment by merryHunter** [comment]
Hi @hitesha14  as far as I remember I didn't manage to fix this error, otherwise I'd respond here..
