### ISSUE TITLE
input_dim has multiple values?

### ISSUE THREAD

**Issue by arushk1** [avisingh599/visual-qa#6]
$ python trainMLP.py 
loaded vgg features
loaded word2vec features...
Traceback (most recent call last):
  File "trainMLP.py", line 114, in <module>
    main()
  File "trainMLP.py", line 62, in main
    model.add(Dense(args.num_hidden_units, input_dim=img_dim+word_vec_dim, init='uniform'))
TypeError: __init__() got multiple values for keyword argument 'input_dim'

Not able to understand this. Seems fine to me. This is the way I'd do it. Insights?

**Comment by avisingh599** [comment]
You got this error without making any changes to the script?

**Comment by arushk1** [comment]
Yes. No changes at all

**Comment by avisingh599** [comment]
I'm unable to get this to reproduce this error on my side. Are you using the same versions of Keras/Theano as I have highlighted in my README?
Try this simple Keras example:
```
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, input_dim=20, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(64, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(2, init='uniform'))
model.add(Activation('softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)
```
This is straight from the Keras README.

**Comment by arushk1** [comment]
Yeah. This does not run. That's odd. I have used keras before... Let me check

**Comment by arushk1** [comment]
Yeah. It was a Keras problem. Someone had opened the same issue on Keras repo. Fixed now.
